import streamlit as st 


st.title("찐오의 설문조사")
st.header("               Made by:찐오")
st.title("설문조사 2 응답 방법:")
st.header("설문조사의 질문을 읽고 질문에 답하여주세요 ✅")
st.header(":D 그럼 시작해볼까여? :0 :l")

a = st.number_input("자는 시간은 몇시인가요?(오후/오전 상관X, 시를 붙이지 말아주세요!✅)")
b = st.text_input("그로우 어 가든을 좋아하나요?(네/아니요)✅")
b = st.text_input("안녕하세요(안녕하세요 :)/안녕히가세요)✅")
b = st.text_input("제일 잠을 빨리 잘것같은 사람이 누구인가요?(파이썬에 온 사람중에!)✅")
b = st.text_input("야채를 좋아하나요?(네/아니요)✅")
b = st.text_input("�մ�ȳմմ�ȳ�e�ϴ�ȳe�ݰ��ȳ✅")
b = st.text_input("이름이 뭔가요?✅")
b = st.text_input("좋아하는 일이 있다면 무엇인가요?✅")
b = st.text_input("좋아하는 음식이 있나요?✅")
b = st.text_input("가장 좋아하는 음식이 무엇인가요?✅")
b = st.text_input("당신은 무슨띠인가요?✅")
b = st.text_input("당신은 꿈에서 일론머스크가 나타나서 테슬라를 줘서 그 테슬라를 타고 도시를 돌아다니다가 차가 급발진을 해버려서 램프를 타고 갑자기 날아가면서 땅에 박히면서 꿈에서 깬적이 있나요?(네/아니요)✅")
b = st.text_input("당신은 한국인이 맞습니까?✅")
b = st.text_input("당신은 얼마인가요?✅")
b = st.text_input("당신은 �մȳ�ȳ�մ�ϴ�ݰ�մ�✅")
b = st.text_input("그로우 어 가든 재산은 얼마인가요(숫자 말고 글씨로 적기!!!!!!!!!)?✅")
a = st.number_input("나이는?✅")
b = st.text_input("당신은 꿈에서 두바이 사람이 되어서 화석 연료를 팔고 부자가 되어서 수퍼카를 사고 좋은 집도 샀는데 갑자기 자동차가 오작동이 나서 당신의 집으로 달려들어서 당신의 집이 박살나는 꿈을 꾸다가 께서 오줌을 지린적이 있나요?✅")
a = st.number_input("언제 테어났나요?(숫자로 적기!)")
b = st.text_input("당신은 쉬는시간을 좋아하나요?✅")
b = st.text_input("당신은 백룸� 빠��մȳ�ȳ�մ�ϴ�ݰ�մ�✅")

b = st.text_input("✅")
b = st.text_input("당신에게 엘레베이터 저주��մȳ 를 겁니�✅")
b = st.header("???: 444444444444✅")
b = st.header("오류가 있었��մȳ✅")
b = st.text_input("후✅")
b = st.text_input("케이팝 데몬 헌터즈를 봤나요✅")
st.title("지금까지 설문조사 2 를 하였습니다!")
st.title("질문에 답해주셔서 감사합니다!")